
FROM python:3.14.3-alpine3.23

WORKDIR /app

COPY ./codigo-python/usuarioLogin.txt .
COPY ./codigo-python/usuarioCadastrado.txt . 
COPY ./codigo-python/canais.txt . 

RUN pip install pyzmq msgpack

CMD ["python", "main.py"]
