FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG FOLDER_NAME
WORKDIR /src

COPY ./codigo-csharp/${FOLDER_NAME}/ .
COPY ./codigo-csharp/Utils/ .
COPY ./codigo-csharp/names.txt .
COPY ./codigo-csharp/channels.txt .

RUN dotnet restore ${FOLDER_NAME}.csproj
RUN dotnet publish ${FOLDER_NAME}.csproj -c Release -o /app/out

FROM mcr.microsoft.com/dotnet/runtime:8.0
ARG FOLDER_NAME
ENV DLL_NAME=${FOLDER_NAME}.dll

WORKDIR /app

COPY --from=build /app/out .
COPY ./codigo-csharp/names.txt .
COPY ./codigo-csharp/channels.txt .

ENTRYPOINT dotnet $DLL_NAME