services:
# -------------- BROKER ---------
  broker:
    build:
      context: .
      dockerfile: Dockerfile-python
    container_name: broker
    volumes:
      - ./broker/broker.py:/app/main.py
    ports:
      - 5555:5555
      - 5556:5556


# ------------- PROXY -----------
  proxy:
    build:
      context: .
      dockerfile: Dockerfile-python
    container_name: proxy
    volumes:
      - ./proxy/proxy.py:/app/main.py
    ports:
      - 5557:5557
      - 5558:5558

# -------------- PYTHON ---------
#  servidor-python:
#    build:
#      context: .
#      dockerfile: Dockerfile-python
#    volumes:
#      - ./codigo-python/servidor.py:/app/main.py # passar caminho real dos arquivos main
#    depends_on:
#      - broker

#  cliente-python:
#    build:
#      context: .
#      dockerfile: Dockerfile-python
#    volumes:
#      - ./codigo-python/cliente.py:/app/main.py # passar caminho real dos arquivos main
#    depends_on:
#      - servidor-python

# -------- RUBY -----------
  servidor-ruby:
     build:
       context: .
       dockerfile: Dockerfile-ruby
     volumes:
       - ./codigo-ruby/servidor.rb:/app/main.rb
     depends_on:
       - broker
       - proxy

  cliente-ruby:
    build:
      context: .
      dockerfile: Dockerfile-ruby
    image: cliente_ruby:gemzmq
    volumes:
      - ./codigo-ruby/cliente.rb:/app/main.rb
    depends_on:
      - servidor-ruby

# -------------- C# -------------
#  servidor-csharp:
#    build:
#      context: .
#      dockerfile: Dockerfile-csharp
#      args:
#        FOLDER_NAME: Servidor
#    depends_on:
#      - broker

#  cliente-csharp:
#    build:
#      context: .
#      dockerfile: Dockerfile-csharp
#      args:
#        FOLDER_NAME: Cliente
#    depends_on:
#      - servidor-csharp

