FROM ruby:4.0.1-alpine3.23

WORKDIR /app

RUN apk add --no-cache \
    build-base \
    zeromq-dev \
    protobuf \
    protobuf-dev

RUN gem install ffi-rzmq google-protobuf

COPY codigo-ruby/ruby-proto.proto .

RUN protoc --ruby_out=. ruby-proto.proto

CMD ["ruby", "main.rb"]
